# Generated by Django 3.2.8 on 2021-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applience_name', models.CharField(max_length=100, unique=True)),
                ('copies', models.PositiveIntegerField(default=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
